# Generated by Django 4.2.17 on 2025-01-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
